// import { IStreamDataResponse } from '../model/type';

// export const dummyLives: IStreamDataResponse[] = [
//   {
//     streamId: 'stream-001',
//     title: '악마의 아이야ㅕㅆ죠?????? 아무도 못 맞혔죠?',
//     url: '/dummy-images/thumbnail-1.png', 
//     userId: 'user-gam',
//     username: 'gamer123',
//     nickname: '시라유키 히나',
//     profileImage: '/dummy-images/thumbnail-1.png', 
//     followers: 1234,
//   },
//   {
//     streamId: 'stream-002',
//     title: '[ 에견녀 찌로 일어났따 ]',
//     url: '/dummy-images/thumbnail-2.png', 
//     userId: 'user-coo',
//     username: 'cookingqueen',
//     nickname: '네네코 마시로',
//     profileImage: '/dummy-images/thumbnail-2.png', 
//     followers: 5678,
//   },
//   {
//     streamId: 'stream-003',
//     title: '( ܸ ⩌⩊⩌ ܸ )',
//     url: '/dummy-images/thumbnail-3.png',
//     userId: 'user-mus',
//     username: 'musiclover',
//     nickname: '강지',
//     profileImage: '/dummy-images/thumbnail-3.png',
//     followers: 4321,
//   },
//   {
//     streamId: 'stream-004',
//     title: '닭도리탕love...',
//     url: '/dummy-images/thumbnail-4.png',
//     userId: 'user-tec',
//     username: 'techgeek',
//     nickname: '카린',
//     profileImage: '/dummy-images/thumbnail-4.png',
//     followers: 876,
//   },
//   {
//     streamId: 'stream-005',
//     title: '남성호르몬충전하는날 (복싱게임1:30)🥊',
//     url: '/dummy-images/thumbnail-5.png',
//     userId: 'user-art',
//     username: 'artcreator',
//     nickname: '나나링 Nanaring',
//     profileImage: '/dummy-images/thumbnail-5.png',
//     followers: 999,
//   },
//   {
//     streamId: 'stream-006',
//     title: '에겐녀의 표본',
//     url: '/dummy-images/thumbnail-6.png',
//     userId: 'user-gam',
//     username: 'gamer123',
//     nickname: '유세라',
//     profileImage: '/dummy-images/thumbnail-6.png',
//     followers: 1234,
//   },
//   {
//     streamId: 'stream-007',
//     title: '🍊🐇딸기맛 몬스터가 좋아요 ⌯･ㅅ･⌯ಣ🍊🐇',
//     url: '/dummy-images/thumbnail-7.png',
//     userId: 'user-coo',
//     username: 'cookingqueen',
//     nickname: '라비타',
//     profileImage: '/dummy-images/thumbnail-7.png',
//     followers: 5678,
//   },
//   {
//     streamId: 'stream-008',
//     title: '채팅은 아니래요',
//     url: '/dummy-images/thumbnail-8.png',
//     userId: 'user-mus',
//     username: 'musiclover',
//     nickname: '임 설',
//     profileImage: '/dummy-images/thumbnail-8.png',
//     followers: 4321,
//   },
//   {
//     streamId: 'stream-009',
//     title: '긴급회의',
//     url: '/dummy-images/thumbnail-9.png',
//     userId: 'user-tod',
//     username: '토다기',
//     nickname: '아주머',
//     profileImage: '/dummy-images/thumbnail-9.png',
//     followers: 2100,
//   },
//   {
//     streamId: 'stream-010',
//     title: '반갑다 X세대 여러분',
//     url: '/dummy-images/thumbnail-10.png',
//     userId: 'user-lif',
//     username: 'lifestyle',
//     nickname: '디디디용',
//     profileImage: '/dummy-images/thumbnail-10.png',
//     followers: 3400,
//   }
// ];